Fix: Modified z-index for draggable components, navbar and tabsBar in both expanded and collapsed states of tabsBar
CircuitVerse/cv-frontend-vue pull request #261
Opened 2024-01-16 21:09 UTC by Chandrachur67

Fixes #260 

#### Describe the changes you have made in this PR -

1. Modified the z-index values to be assigned to draggable elements during the "mousedown" event (set to previous values similar to circuitverse.org/simulator)

2. Modified code for the event listener of the tabsBar expand and collapse button
- when expanded, added inline CSS to the navbar and tabsBar to have a higher z-index so that they appear on top of draggable panels.
- when collapsed, removed the inline styling to revert back to original values so that draggable panels appear on top of everything.

### Screenshots of the changes (If any) -

### Before 

#### Once draggable components are moved to overlap with the top section, it loses the functionality of moving further
<img width="1440" alt="Screenshot 2024-01-17 at 1 57 57 AM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/7a2a2b6a-e1b5-4aa7-8a41-50af01306fd9">

### After

#### tabsBar not expanded state => draggable panels on top of everything. 
<img width="1440" alt="Screenshot 2024-01-17 at 1 49 04 AM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/e52ac47c-fd3b-4747-a7e8-054c4edc89a5">

#### tabsBar expanded state => navbar and tabsBar on top of draggable components for better accessibility of tabsBar
<img width="1440" alt="Screenshot 2024-01-17 at 1 49 13 AM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/84c22c8f-928a-43a2-904d-986c50e930b3">

#### Video demonstrating the change

https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/4956b3f1-df26-48ef-9ee4-a19a5fa9134e

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-01-16 21:15 UTC, Chandrachur67 commented
Hey @Arnabdaz, Please take a look at this. I have fixed the z-indexes following the requirements you specified.

2024-01-17 05:32 UTC, Arnabdaz requested changes
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/96580571/b117cea4-b3a5-4012-b97c-6e796aa26bda)
the drop-down menu is below the tabsbar & panels fix this issue

2024-01-17 08:44 UTC, Chandrachur67 commented
Sure. Sorry for the glitch. I will fix this.

### Clarification needed
However I need one more clarification: The z-index of dropdown menu is controlled by the z-index of the navbar. So in collapsed state, even if any a nav-dropdown item is expanded due to higher z-index of draggable components it will not come on top of draggable-component. Is this behaviour ok? if ok then I have done it and mentioned all the changes below.

But if you want me change this behaviour, then I have to modify and add event-listeners to some components of navbar and it will make the changes complex bacuase that is probably controlled by aria-expanded and data-toggle. please let me know what you want. 


### Propsed Solution
This is the behaviour I am trying to implement: 
Changing the value of z-index of #tabsBar in TabsBar.vue to 99.

### In collapsed mode 
#### z-index : draggable-components > navbar > tabsBar

### In expanded mode 
#### z-index: navbar > tabsBar > draggable-components

The exact values I am planning to use:
| tabsBar state | navbar | tabsBar | draggable components |
|---------------|--------|---------|------------------------|
| Expanded      |   103  |   102   |           <102         |
| Collapsed     |   100  |   99    | (101 for selected and 100 for others) |

### Images
#### In collapsed mode
<img width="551" alt="Screenshot 2024-01-17 at 12 46 52 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/26590c4d-049f-45db-879e-5d1931fe714c">
<img width="659" alt="Screenshot 2024-01-17 at 12 47 13 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/c7b041f3-e8b9-49f6-a15c-54062bddcb3b">

#### In expanded mode
<img width="768" alt="Screenshot 2024-01-17 at 12 48 30 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/73e38c51-1071-4808-98ae-4000759a1944">
<img width="590" alt="Screenshot 2024-01-17 at 12 48 06 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/5d241a7d-83fd-48a6-b66e-2a98dec0da33">

2024-01-20 20:27 UTC, Chandrachur67 commented
@Arnabdaz  @Prerna-0202  it would be great if you could take a look at this.

2024-01-21 20:28 UTC, b-harsh commented
i have got some ideas should i start working on this issue @Chandrachur67 @Arnabdaz

2026-05-28 15:44 UTC, aryanndwi123 commented
Closing this PR!!! Since there are several merge conflitcs and its a stale PR

2026-05-28 15:44 UTC, closed without merging