Console warnings #279
CircuitVerse/cv-frontend-vue pull request #287
Opened 2024-03-16 16:38 UTC by niladrix719

Fixes #279 

#### Describe the changes you have made in this PR -

- unwanted console logs removed
- transition item-key missing warning removed

### Screenshots of the changes (If any) -

![Screenshot 2024-03-16 at 10 04 25 PM](https://github.com/CircuitVerse/cv-frontend-vue/assets/91966855/8b5da23c-fb04-4eac-b14f-6afdb8e27f2a)

Note: The warning related to the transition group is a issue related to vue.draggable.next library which currently stays but if i find a way to fix it i will create a follow up pr

2024-03-16 17:32 UTC, Arnabdaz requested changes

2024-03-16 17:32 UTC, Arnabdaz commented on src/components/DialogBox/OpenOffline.vue
>      }
i guess we can remove this.

2024-03-16 17:42 UTC, niladrix719 commented on src/components/DialogBox/OpenOffline.vue
>      }
yes removed

2024-03-18 20:57 UTC, Arnabdaz approved these changes

2024-03-18 20:57 UTC, merged