fix(gsoc'24): updates and bug fixes from the main simulator
CircuitVerse/cv-frontend-vue pull request #314
Opened 2024-05-16 14:58 UTC by niladrix719

Fixes [#107](https://github.com/CircuitVerse/upptime/issues/107)

Updates and Bug fixes from the main Simulator

2024-05-20 05:19 UTC, vedant-jain03 requested changes

2024-05-20 05:19 UTC, vedant-jain03 commented on src/simulator/src/tutorials.js
> +            description: 'This panel helps you test your circuit correctness by observing how your circuit responds under different test cases, ensuring a thorough and effective validation process.',
can we make it i18n?

2024-07-31 10:30 UTC, tachyons commented
I think this will undo some of the optimizations made by @JoshVarga . Why was this PR delayed ? you mentioned that all the updates from the legacy simulator are already copied, right ?

2024-07-31 12:48 UTC, niladrix719 commented
@tachyons , I guess there was some miscommunication on my end. The PR was there way back but wasn't merged before

2024-07-31 12:56 UTC, tachyons commented
@niladrix719  Could you create separate PRs to copy changes. PR can't be reviewed in this form. Also give highest priority for this.

2024-07-31 12:56 UTC, closed without merging

2024-08-01 12:19 UTC, niladrix719 commented
created Separate PRs - #345, #346, #347, #348, #349, #350, #351, #352, #353, #354, #355, #356