feat(gsoc'24): Typescript Integration in eventQueue file
CircuitVerse/cv-frontend-vue pull request #338
Opened 2024-07-17 12:30 UTC by niladrix719

Fixes #

#### Describe the changes you have made in this PR -

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

2024-07-25 14:44 UTC, JoshVarga commented on src/simulator/src/eventQueue.ts
>  export default class EventQueue {
Please change to non-default export. `export class EventQueue {`

2024-07-26 23:35 UTC, JoshVarga submitted a review, later dismissed

2024-07-27 00:22 UTC, JoshVarga requested changes
Merge with main otherwise looks good

2024-07-27 17:20 UTC, vedant-jain03 approved these changes

2024-07-27 17:21 UTC, Arnabdaz approved these changes

2024-07-27 23:18 UTC, JoshVarga approved these changes

2024-07-27 23:18 UTC, merged